version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rails
    versions:
    - ">= 6.0.a, < 6.1"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.1
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.0
    - 3.12.1
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  - dependency-name: jasmine
    versions:
    - 3.6.0
