FROM ruby:3.2.2-bullseye

EXPOSE 3000
RUN gem update bundler --no-doc
RUN SECRET_KEY_BASE=`rails secret` RAILS_ENV=production STAFF_SERVICE_URL=http://example.com SERVICE_URL=http://example.com bin/rake assets:precompile --trace

ENTRYPOINT ["./run.sh"]
