apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prison-visits-public-production
  namespace: prison-visits-booking-production
spec:
  secretName: prison-visits-public-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'prisonvisits.service.gov.uk'
  acme:
    config:
    - domains:
      - 'prisonvisits.service.gov.uk'
      dns01:
        provider: route53-cloud-platform
