generic-service:
  image:
    repository: ghcr.io/ministryofjustice/prison-visits-public
    tag: app_version # overridden at deployment time
    port: 3000

  containerCommand: ["sh", "-c", "bundle exec puma -p 3000 -C ./config/puma_prod.rb --pidfile /tmp/server.pid"]

  fullnameOverride: "prison-visits-public"

  service:
    enabled: true
    type: ClusterIP
    port: 3000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 20%

  ingress:
    enabled: true
    tlsSecretName: prison-visits-public-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=hmpps-prison-visits-booking,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS,setvar:tx.paranoia_level=3"
      # Block Detectify scanner with 418
      SecRule REQUEST_HEADERS:User-Agent "@pm detectify Detectify DETECTIFY" "id:800003,phase:1,deny,status:418,log,tag:github_team=hmpps-prison-visits-booking,tag:namespace={{ .Release.Namespace }}"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  livenessProbe:
    httpGet:
      path: /ping
      port: 3000

  readinessProbe:
    httpGet:
      path: /ping
      port: 3000

  namespace_secrets:
    hmpps-auth-secrets:
      NOMIS_USER_OAUTH_CLIENT_ID: NOMIS_USER_OAUTH_CLIENT_ID
      NOMIS_USER_OAUTH_CLIENT_SECRET: NOMIS_USER_OAUTH_CLIENT_SECRET
    secrets:
      NOMIS_OAUTH_CLIENT_ID: NOMIS_OAUTH_CLIENT_ID
      NOMIS_OAUTH_CLIENT_SECRET: NOMIS_OAUTH_CLIENT_SECRET
      GOV_NOTIFY_API_KEY: GOV_NOTIFY_API_KEY
    use-vsip:
      USE_VSIP: USE_VSIP
    prison-visits-public-secrets:
      GA_TRACKING_ID: ga_tracking_id
      WEB_CONCURRENCY: rails_web_concurrency
      SENTRY_JS_DSN: sentry_js_dsn
      SENTRY_DSN: sentry_dsn
      SECRET_KEY_BASE: secret_key_base
    prison-visits-rds-instance-output:
      DATABASE_URL: url

  env:
    PRODUCT_ID: "DPS031"
    KUBERNETES_DEPLOYMENT: "true"

generic-prometheus-alerts:
  targetApplication: prison-visits-public
  alertSeverity: visits-alerts
  businessHoursOnly: false
