apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prison-visits-public
  namespace: prison-visits-booking-staging
spec:
  selector:
    matchLabels:
      app: prison-visits-public
  namespaceSelector:
    matchNames:
    - prison-visits-booking-staging
  endpoints:
  - port: metrics
    interval: 15s