apiVersion: v1
kind: Service
metadata:
  name: prison-visits-public
  namespace: prison-visits-booking-staging
  labels:
    app: prison-visits-public
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: prison-visits-public
